### ISSUE TITLE
iOS binaries support.

### ISSUE THREAD

**Issue by prabhav-mehra** [SDWebImage/libheif-Xcode#4]
Hi, I was wondering if there is a way to get iOS binaries of libheif with libde256 decoding, i.e. getting .a files. Building the project didn’t give me those.

**Comment by prabhav-mehra** [comment]
@dreampiggy

**Comment by dreampiggy** [comment]
Xcodeproj, so why can't ?

You can change framework 's `MACH_O_TYPE` into `staticlib` and grab the `MachO` ar archive from framework bundle

**Comment by prabhav-mehra** [comment]
I was able to get the .a file using https://github.com/strukturag/libheif/issues/16#issuecomment-1651136026. Does the libheif include the libde265 decoder/built with it? 

I am using it for a .net project and currently it gives me dll not found error so I am unable to test that at the moment.

**Comment by dreampiggy** [comment]
You ask some **General solution** about this question:

> How to build static ar archive on macOS Xcode Project...

So this is not specified to this `libheif-xcode` project or something. You can even search some step-by-step manual online.

I already answer some tip, for example:

1. `static framework` is actually`a special folder which contains static arvhive file into it`, nothing magic. To build static framework, you can just change Xcode project build settings `MACH_O_TYPE` to `staticlib` (instead of `dylib`) and build
2. To build xcodeproject contains dependencies like [Carthage](https://github.com/Carthage/Carthage) dependency, run that package manager firstly. (Carthage is a tool which manage .framework dependeicies) It will build each dependencies's framework into that `Carthage/Build` folder, then you can just grab them
